### ISSUE TITLE
Sampler gives NaN values

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/skillful_nowcasting#10]
**Describe the bug**
The Sampler gives NaN values when being used in the generator. 

**To Reproduce**
The unit tests have it happen in test_generator, and test_sampler

**Expected behavior**
No NaN values should exist in the output

**Additional context**
From unit tests, each of the layers in the Sampler don't return NaNs, so not sure why it does so. It seems to happen usually after `g3` or `ConvGRU3` layers.

**Comment by sjjlr** [comment]
I don't understand why the authors transform the radar echo dBZ to rain rate using Z-R relationship? Why don't they directly use  radar echo reflectivity?

**Comment by xinzhuang** [comment]
Thanks for your implementation of dgmr! It's organization is clear,and easy to read. 

When I run the test_model.py,I also found the nan values in sampler's output.  I check the ConvGRU.py, found that the bug may be aroused by `spectral_norm`  function.

According to PyTorch [spectral_norm doc](https://pytorch.org/docs/stable/generated/torch.nn.utils.spectral_norm.html#torch.nn.utils.spectral_norm) ,   I use `torch.nn.utils.parametrizations.spectral_norm()`  instead,  also `spectral_norm` in common.py, and it works fine now. I Think you should have a try. 

Though I don't know why, hopefully it helps. Thanks.

**Comment by jacobbieker** [comment]
Oh, thanks for figuring that out! I'll update it to use that now then too

**Comment by jacobbieker** [comment]
It worked! Thanks so much
