### ISSUE TITLE
Add Pre-trained weights from DeepMind and upload to HuggingFace

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/skillful_nowcasting#4]
## Detailed Description

DeepMind just sorta released the model here: https://github.com/deepmind/deepmind-research/tree/master/nowcasting
The model definition code still doesn't seem to be available, but possibly we can somewhat reverse-engineer from the TF-Hub link? And see what differences there might be, or how to adapt the TF model weights to PyTorch

## Context

This would give us a precipitation nowcasting model, which could be quite helpful for forecasting, as well as a pre-trained model to finetune on cloud predictions, or possibly solar predictions directly.

**Comment by jacobbieker** [comment]
Have the model weights locally now, and can print out the layers+weights from the `SavedModel` that was released, just not in a very easy format to view!

**Comment by JackKelly** [comment]
Wow, that was fast, great work!

**Comment by tcapelle** [comment]
Wow, I want to follow this!
Probably the guys from HF have a lot of experience porting models from TF to PT, also Ross from timm.
