### ISSUE TITLE
Issue with loading weights from Hugging Face

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/skillful_nowcasting#65]
## Describe the bug
It is described in https://huggingface.co/openclimatefix/dgmr/discussions/1

**Comment by RayLinzu** [comment]
I solved the problem by adding the use_token parameter to hub_mixin.py. thanks

**Comment by suleman1412** [comment]
Hi @jacobbieker I would like to work on this issue, is this still open?

**Comment by jacobbieker** [comment]
Hi, this one actually has been fixed in #67
