### ISSUE TITLE
Fix CI testing

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/skillful_nowcasting#71]
Current CI tests dont work. Would someone be able to fix this?

**Comment by Mews** [comment]
I think this is an issue with the github action you're using https://github.com/openclimatefix/.github/blob/main/.github/workflows/python-test.yml
Looks like they're trying to use a linux command on mac-os.
You can just not test on macos-latest, but I can write a new workflow that will replace the functionality of the one you were using previously.

**Comment by peterdudfield** [comment]
To keep the code as simple as possible, maybe its worth just turning of the CI for the mac
This can be done with this option - https://github.com/openclimatefix/.github/blob/main/.github/workflows/python-test.yml#L25

**Comment by Mews** [comment]
Yeah I mean you pick the solution you see fit.
I've opened the pr with the new workflow either way.

**Comment by peterdudfield** [comment]
I think i would prefer just turning the CI off for mac, keeps things nice and simple and then we are reusing some of the CI code. 

Would you @Mews be interested in doing that?

**Comment by Mews** [comment]
Alrighty :P

**Comment by Mews** [comment]
I'm gonna close my other pr then 👍
